# Generated by Django 4.1 on 2022-09-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expensecategorie_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseCategorie',
            new_name='ExpenseCategory',
        ),
        migrations.RenameModel(
            old_name='IncomeCategorie',
            new_name='IncomeCategory',
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'expense categories'},
        ),
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'verbose_name_plural': 'income categories'},
        ),
    ]
