# Generated by Django 4.1 on 2022-09-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_expensecategorie_expensecategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='expensecategory',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='category',
            new_name='incomecategory',
        ),
    ]
