# Generated by Django 4.1 on 2022-09-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_category_expense_expensecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecategory',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
