# Generated by Django 4.1 on 2022-09-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_incomecategory_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expensecategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='incomecategory',
            new_name='category',
        ),
    ]
