# Generated by Django 4.1 on 2022-09-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_expensecategory_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='incomecategory',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('name',)},
        ),
    ]
